# Generated by Django 5.2.17 on 2026-09-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Adiestramiento básico', 'Adiestramiento básico'), ('Cachorros y socialización', 'Cachorros y socialización'), ('Modificación de conducta', 'Modificación de conducta'), ('Ansiedad por separación', 'Ansiedad por separación'), ('Entrenamiento avanzado', 'Entrenamiento avanzado'), ('Agility y deportes caninos', 'Agility y deportes caninos'), ('Paseos y ejercicio', 'Paseos y ejercicio')], max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('imagen', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
