# Generated by Django 5.2.17 on 2026-09-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('adiestrador', 'Adiestrador'), ('administrador', 'Administrador')], default='cliente', max_length=20)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_aprobacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='aprobado', max_length=20)),
                ('certificado', models.CharField(blank=True, max_length=255, null=True)),
                ('especialidades_solicitadas', models.JSONField(blank=True, default=list)),
                ('especialidades', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
