# Generated by Django 5.2.17 on 2026-09-11 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('duracion', models.CharField(choices=[('corto', 'Corto plazo (menos de 1 mes)'), ('mediano', 'Mediano plazo (1 a 6 meses)'), ('largo', 'Largo plazo (6 meses a 1 año)'), ('muy_largo', 'Muy largo plazo (más de 1 año)')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('perro_nombre', models.CharField(max_length=100)),
                ('perro_raza', models.CharField(max_length=100)),
                ('perro_edad', models.IntegerField()),
                ('perro_peso', models.FloatField()),
                ('perro_sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('perro_esterilizado', models.BooleanField()),
                ('perro_vacunas_al_dia', models.BooleanField()),
                ('perro_conducta', models.TextField(blank=True, default='')),
                ('perro_salud', models.TextField(blank=True, default='')),
                ('perro_foto', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('adiestrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_como_adiestrador', to='users.usuario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_como_cliente', to='users.usuario')),
            ],
        ),
    ]
