# Generated by Django 5.2.17 on 2026-09-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('completado', 'Completado'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
