# Generated by Django 5.2.17 on 2026-09-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Collar', 'Collar'), ('Pechera', 'Pechera'), ('Correa', 'Correa'), ('Impermeable', 'Impermeable'), ('Juguete', 'Juguete'), ('Comida', 'Comida'), ('Producto de aseo', 'Producto de aseo'), ('Accesorio', 'Accesorio')], max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('imagen', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
