# Generated by Django 5.2.17 on 2026-09-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('esterilizado', models.BooleanField()),
                ('vacunas_al_dia', models.BooleanField()),
                ('conducta', models.TextField(blank=True, default='')),
                ('salud', models.TextField(blank=True, default='')),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='users.usuario')),
            ],
        ),
    ]
